#### Activate Interfaces ####
- name: "Activating Link"
  cisco.ios.ios_interfaces:
    config:
      - name: GigabitEthernet0/1
        description: "to R.Core"
        duplex: full
        enabled: true

      - name: GigabitEthernet0/3
        description: "to Client"
        duplex: full
        enabled: true

    state: replaced

- name: "Adding IP on R2 Interfaces"
  cisco.ios.ios_l3_interfaces:
    config:
      - name: GigabitEthernet0/1
        ipv4:
          - address: 192.168.3.2/30
        
      - name: GigabitEthernet0/3
        ipv4:
          - address: 192.168.6.1/24
              
      - name: Loopback0
        ipv4:
          - address: 2.2.2.2/32

    state: replaced


#### OSPF Conf ####
- name: "OSPF R2"
  cisco.ios.ios_ospfv2:
    config:
      processes:

        - process_id: 100
          router_id: 2.2.2.2
          network:
            - { address: 192.168.3.0, wildcard_bits: 0.0.0.3, area: '0' }
            - { address: 192.168.6.0, wildcard_bits: 0.0.0.255, area: '0' }
            - { address: 2.2.2.2, wildcard_bits: 0.0.0.0, area: '0' }

          passive_interfaces: 
            interface:
              name: [ 'Loopback0', 'GigabitEthernet0/3' ]
              set_interface: yes

          log_adjacency_changes:
            set: yes

    state: merged


#### Create DHCP Pool ####
- name: create POOL
  cisco.ios.ios_config:
    parents: ip dhcp pool net
    lines: 
      - network 192.168.6.0 /24
      - def 192.168.6.1
      - dns 8.8.8.8
      - exit

