#### Activate Interfaces ####
- name: "Activating Link"
  cisco.ios.ios_interfaces:
    config:
      - name: GigabitEthernet0/1
        description: "Bundle"
        duplex: full
        enabled: true
      
      - name: GigabitEthernet0/2
        description: "Bundle"
        duplex: full
        enabled: true

      - name: GigabitEthernet0/3
        description: "Bundle"
        duplex: full
        enabled: true

      - name: GigabitEthernet0/4
        description: "Bundle"
        duplex: full
        enabled: true

    state: merged

- name: "Adding IP on R2 Interfaces"
  cisco.ios.ios_l3_interfaces:
    config:
      - name: GigabitEthernet0/1
        ipv4:
          - address: 192.168.1.2/30

      - name: GigabitEthernet0/2
        ipv4:
          - address: 192.168.2.2/30
        
      - name: GigabitEthernet0/3
        ipv4:
          - address: 192.168.4.1/30

      - name: GigabitEthernet0/4
        ipv4:
          - address: 192.168.5.1/30
              
      - name: Loopback0
        ipv4:
          - address: 2.2.2.2/32

    state: merged


#### OSPF Conf ####
- name: "OSPF R2"
  cisco.ios.ios_ospfv2:
    config:
      processes:

        - process_id: 100
          router_id: 2.2.2.2
          network:
            - { address: 192.168.1.0, wildcard_bits: 0.0.0.3, area: '0' }
            - { address: 192.168.2.0, wildcard_bits: 0.0.0.3, area: '0' }
            - { address: 192.168.4.0, wildcard_bits: 0.0.0.3, area: '0' }
            - { address: 192.168.5.0, wildcard_bits: 0.0.0.3, area: '0' }
            - { address: 2.2.2.2, wildcard_bits: 0.0.0.0, area: '0' }

          passive_interfaces: 
            interface:
              name: [ 'Loopback0' ]
              set_interface: yes

          log_adjacency_changes:
            set: yes

    state: merged