# Author: https://www.github.com/mueherizky


---
  - name: "Manage L2 Interfaces"
    hosts: switches
    gather_facts: no
    tasks:

###### Configuring Interfaces Mode Access #######
      - name: "Configuring Access Mode"
        cisco.ios.ios_l2_interfaces:
          config:
            - name: GigabitEthernet0/2
              access:
                vlan: 2
              mode: access

            - name: GigabitEthernet0/3
              access:
                vlan: 3
              mode: access

            - name: GigabitEthernet1/0
              access:
                vlan: 4
              mode: access

            - name: GigabitEthernet1/3
              access:
                vlan: 5
              mode: access

          state: replaced


##### Configuring Interfaces Mode Trunk #######

############### Switch 1 ###############
  - hosts: s1.lab
    gather_facts: no
    tasks:

        - name: "Configure Trunk S1"
          cisco.ios.ios_l2_interfaces:
            config:
              - name: GigabitEthernet1/1
                trunk:
                  allowed_vlans: 2-5
                  encapsulation: dot1q
                  native_vlan: 1000
                mode: trunk

            state: replaced


############### Switch 2 ##############
  - hosts: s2.lab
    gather_facts: no
    tasks:

        - name: "Configure Trunk S2"
          cisco.ios.ios_l2_interfaces:
            config:
              - name: GigabitEthernet1/1
                trunk:
                  allowed_vlans: 2-5
                  encapsulation: dot1q
                  native_vlan: 1000
                mode: trunk

              - name: GigabitEthernet1/2
                trunk:
                  allowed_vlans: 2-5
                  encapsulation: dot1q
                  native_vlan: 1000
                mode: trunk

            state: replaced


############### Switch 3 ###############
  - hosts: s3.lab
    gather_facts: no
    tasks:

        - name: "Configure Trunk S3"
          cisco.ios.ios_l2_interfaces:
            config:
              - name: GigabitEthernet1/2
                trunk:
                  allowed_vlans: 2-5
                  encapsulation: dot1q
                  native_vlan: 1000
                mode: trunk

            state: replaced
