# Author: https://www.github.com/mueherizky

---

  - name: "Configure Routers"
    hosts: routers
    gather_facts: false
    roles: 
      - routers

  - hosts: core
    gather_facts: false
    roles: 
      - core

  - hosts: r_one
    gather_facts: false
    roles: 
      - r_one

  - hosts: r_two
    gather_facts: false
    roles: 
      - r_two

  - name: "Configure Switch"
    hosts: switches
    gather_facts: false
    pre_tasks:
    roles: 
      - switches

  - hosts: s_one
    gather_facts: false
    pre_tasks:
    roles: 
      - s_one


