- name: Configure Banner Login
  cisco.ios.ios_banner:
    banner: login
    text: |
      Welcome to Router 2
      You can configure it anything you want
      Be carefull with your configuration!
      Look what you type on screen!
    state: present
  
- name: Configure Motd Banner
  cisco.ios.ios_banner:
    banner: motd
    text: |
      Hello, How are you today?
      I hope you fine today.
      Let's login with your account!
    state: present

- name: Configure IP
  cisco.ios.ios_l3_interfaces:
    config:
      - name: GigabitEthernet0/1
        ipv4:
          - address: 10.0.1.2/30
      - name: GigabitEthernet0/2
        ipv4:
          - address: 10.0.3.1/29
      - name: Loopback0
        ipv4:
          - address: 2.2.2.2/32
    state: merged

- name: Activate Interfaces Link
  cisco.ios.ios_interfaces:
    config:
      - name: GigabitEthernet0/1
        description: Connect to R1
        enabled: yes
      - name: GigabitEthernet0/2
        description: Connect to Client
        enabled: yes
    state: merged

- name: Add OSPF Route 
  cisco.ios.ios_ospfv2:
    config:
      processes: 
        - process_id: 100
          router_id: 2.2.2.2
          network:
            - { address: 10.0.1.0, wildcard_bits: 0.0.0.3, area: '0' }
            - { address: 10.0.3.0, wildcard_bits: 0.0.0.3, area: '0' }
            - { address: 2.2.2.2, wildcard_bits: 0.0.0.0, area: '0' }

          default_information:
            originate: yes 
            always: yes

          auto_cost:
            reference_bandwidth: 1000
            set: yes

          passive_interfaces: 
            interface:
              name: [ Loopback0 ]
              set_interface: yes  

          log_adjacency_changes:
            set: yes

    state: merged

- name: Add dhcp server
  cisco.ios.ios_config:
    parents: ip dhcp pool net_client_R2
    lines:
      - network 10.0.3.0 /29
      - default 10.0.3.1
