#### Activate Interfaces ####
- name: "Activating Link"
  cisco.ios.ios_interfaces:
    config:
      - name: GigabitEthernet0/3
        description: "Bundle"
        duplex: full
        enabled: true
      
      - name: GigabitEthernet0/4
        description: "Bundle"
        duplex: full
        enabled: true

      - name: GigabitEthernet0/5
        description: "to Client"
        duplex: full
        enabled: true

      - name: GigabitEthernet0/6
        description: "to Client"
        duplex: full
        enabled: true

    state: merged

- name: "Adding IP on R3 Interfaces"
  cisco.ios.ios_l3_interfaces:
    config:
      - name: GigabitEthernet0/3
        ipv4:
          - address: 192.168.4.2/30

      - name: GigabitEthernet0/4
        ipv4:
          - address: 192.168.5.2/30

      - name: GigabitEthernet0/5
        ipv4:
          - address: 192.168.6.1/27

      - name: GigabitEthernet0/6
        ipv4:
          - address: 192.168.7.1/27
              
      - name: Loopback0
        ipv4:
          - address: 3.3.3.3/32

    state: merged


#### OSPF Conf ####
- name: "OSPF R3"
  cisco.ios.ios_ospfv2:
    config:
      processes:

        - process_id: 100
          router_id: 3.3.3.3
          network:
            - { address: 192.168.5.0, wildcard_bits: 0.0.0.3, area: '0' }
            - { address: 192.168.6.0, wildcard_bits: 0.0.0.31, area: '0' }
            - { address: 192.168.7.0, wildcard_bits: 0.0.0.31, area: '0' }
            - { address: 3.3.3.3, wildcard_bits: 0.0.0.0, area: '0' }

          passive_interfaces: 
            interface:
              name: [ 'GigabitEthernet0/5', 'GigabitEthernet0/6', 'Loopback0' ]
              set_interface: yes

          log_adjacency_changes:
            set: yes

    state: merged